### PR TITLE
Android app - web based

### PR DESCRIPTION
**Pull request by manimaran96**
Hi Mozilla team,

I have some works on android side.
I hope it is need full.

### CODE REVIEW

**Comment by phirework** [comment]
Hi @manimaran96, thank you so much for your PR and for being interested in contributing to Common Voice! I just wanted to drop you a note and let you know that unfortunately, we don't have the engineering resources to thoroughly review this right now. We're in the middle of thinking about our product roadmap for the next year, and I can't say where native apps will land on that roadmap, if at all. 

In the meantime, if you have any suggestions for a test plan as to how to properly QA this PR, maybe someone in the community can pick it up? Thanks so much for being patient.

**Comment by MichaelKohler** [comment]
Are there more information regarding the native app by now?

**Comment by manimaran96** [comment]
https://f-droid.org/en/packages/org.commonvoice.saverio/

https://github.com/Sav22999/common-voice-android

**Comment by phirework** [comment]
As the Mozilla team no longer supports any of the native mobile apps, I'm going to close this PR.

**Pull request closed without merging**
