### PR TITLE
Added Swahili data for initial PR

### PR DESCRIPTION
**Pull request by Mujerry**
batch-1-01-11-2021.xlsx

1. Number of sentences: **99,495**
2. Error ratio from the QA: **4.8%**
3. Reviews
   - [Michael Killo](https://github.com/AI-Lab-Makerere/swahili-cv-validation/blob/master/data/batch-1-01-11-2021/validated/Michael%20Killo.xlsx)
   - [Mwahija Juma Mkenge](https://github.com/AI-Lab-Makerere/swahili-cv-validation/blob/master/data/batch-1-01-11-2021/validated/Mwahija%20Juma%20Mkenge.xlsx)
   - [Sylivester Richard](https://github.com/AI-Lab-Makerere/swahili-cv-validation/blob/master/data/batch-1-01-11-2021/validated/Sylivester%20Richard.xlsx)

### CODE REVIEW

**Comment by phirework** [comment]
Thank you for submitting this! Can you please clarify the source of your data and what the license is?

**Comment by Mujerry** [comment]
> Thank you for submitting this! Can you please clarify the source of your data and what the license is?



The data was collected from the community of creators in Tanzania (we have students who created Swahili sentences from the scratch) and some of the data was captured from news websites.
**License:CC0**

**Comment by phirework** [comment]
@Mujerry For the data that was captured from news websites, can you describe your data capturing process and provide the news websites that were used? News reporting is generally copyrighted to the news organization and is not CC-0.

**Comment by Mujerry** [comment]
> @Mujerry For the data that was captured from news websites, can you describe your data capturing process and provide the news websites that were used? News reporting is generally copyrighted to the news organization and is not CC-0.

We have removed data collected from the news sites.
New dataset has **76708** sentences collected from community of creators in Tanzania

**Comment by Heyhillary** [comment]
Hello @Mujerry,

Is it possible if you could share with us the link or repo with the new dataset, please ?

**Comment by Mujerry** [comment]
> Hello @Mujerry,
> 
> Is it possible if you could share with us the link or repo with the new dataset, please ?

@Heyhillary the new dataset can be found in this [repo](https://github.com/AI-Lab-Makerere/swahili-cv-validation/blob/master/data/batch-1-01-11-2021/batch-1-08-11-2021-no-news-data.xlsx)

**Comment by Heyhillary** [comment]
Hey @Mujerry,

For QA I reviewed some of the sentences and found two areas of concern. Firstly I found a few sentences from  

[Tanzanian Government website](https://www.kilimo.go.tz/index.php/sw/highlights/view/katibu-mkuu-kilimo-apongeza-taasisi-za-uzalishaji-mbegu-nchini) "akieleza sababu ya mashamba hauyo kugeuka pori mwenyekiti wa kikundi cha wakulima wa chai". 

[BBC Swahili](https://www.instagram.com/p/CJGi7urFMSE/) "Rais Vladimir Putin amesema jeshi la Urusi limejihami kwa kombora lisiloweza kuzuiwa na Marekani"

Unfortunately, this cannot be included as the text is not clearly marked under [public domain](https://github.com/common-voice/community-playbook/blob/master/sub_pages/Publicdomain(1).pdf). 

Can you please clarify the list of sources you used to create the sentences ? Here an example from the [Catalan communities](https://github.com/TeMU-BSC/catalan_CC0_sentences) that have gone through a similar process.

If you have any questions please let me know.

**Comment by Mujerry** [comment]
> Hey @Mujerry,
> 
> For QA I reviewed some of the sentences and found two areas of concern. Firstly I found a few sentences from
> 
> [Tanzanian Government website](https://www.kilimo.go.tz/index.php/sw/highlights/view/katibu-mkuu-kilimo-apongeza-taasisi-za-uzalishaji-mbegu-nchini) "akieleza sababu ya mashamba hauyo kugeuka pori mwenyekiti wa kikundi cha wakulima wa chai".
> 
> [BBC Swahili](https://www.instagram.com/p/CJGi7urFMSE/) "Rais Vladimir Putin amesema jeshi la Urusi limejihami kwa kombora lisiloweza kuzuiwa na Marekani"
> 
> Unfortunately, this cannot be included as the text is not clearly marked under [public domain](https://github.com/common-voice/community-playbook/blob/master/sub_pages/Publicdomain(1).pdf).
> 
> Can you please clarify the list of sources you used to create the sentences ? Here an example from the [Catalan communities](https://github.com/TeMU-BSC/catalan_CC0_sentences) that have gone through a similar process.
> 
> If you have any questions please let me know.

@Heyhillary 
We have updated the datasets to only include sentences that were generated from contributors. The new dataset has 30159 sentences and the data and description can be found [here](https://github.com/AI-Lab-Makerere/swahili-cv-validation/tree/master/data/batch-1-01-11-2021). We are working to secure agreement from some of the news websites to include their data in future PR's.

**Comment by phirework** [comment]
Great, thanks for the updates @Mujerry! The last thing I need before I can accept this merge is that the sentences actually need to be in a flat text file, with one sentence per line. Here's [an example of what such a file looks like](https://github.com/common-voice/common-voice/blob/main/server/data/sw/wiki.sw.txt) - you should be able to just copy and paste the sentences out of the relevant column in the `.xslx` file and paste it into a plaintext editor like Notepad or Sublime Text and save it as a `.txt` file.

**Comment by Mujerry** [comment]
> Great, thanks for the updates @Mujerry! The last thing I need before I can accept this merge is that the sentences actually need to be in a flat text file, with one sentence per line. Here's [an example of what such a file looks like](https://github.com/common-voice/common-voice/blob/main/server/data/sw/wiki.sw.txt) - you should be able to just copy and paste the sentences out of the relevant column in the `.xslx` file and paste it into a plaintext editor like Notepad or Sublime Text and save it as a `.txt` file.

@phirework Thanks for the update, I have updated the PR with the `txt ` and removed the `xlsx` file.  The [txt file](https://github.com/AI-Lab-Makerere/swahili-cv-validation/blob/master/data/batch-1-01-11-2021/batch-1-19-11-2021-contributors-set.txt) has also been uploaded to this [repo](https://github.com/AI-Lab-Makerere/swahili-cv-validation).

**Comment by Heyhillary** [comment]
> > Hey @Mujerry,
> > For QA I reviewed some of the sentences and found two areas of concern. Firstly I found a few sentences from
> > [Tanzanian Government website](https://www.kilimo.go.tz/index.php/sw/highlights/view/katibu-mkuu-kilimo-apongeza-taasisi-za-uzalishaji-mbegu-nchini) "akieleza sababu ya mashamba hauyo kugeuka pori mwenyekiti wa kikundi cha wakulima wa chai".
> > [BBC Swahili](https://www.instagram.com/p/CJGi7urFMSE/) "Rais Vladimir Putin amesema jeshi la Urusi limejihami kwa kombora lisiloweza kuzuiwa na Marekani"
> > Unfortunately, this cannot be included as the text is not clearly marked under [public domain](https://github.com/common-voice/community-playbook/blob/master/sub_pages/Publicdomain(1).pdf).
> > Can you please clarify the list of sources you used to create the sentences ? Here an example from the [Catalan communities](https://github.com/TeMU-BSC/catalan_CC0_sentences) that have gone through a similar process.
> > If you have any questions please let me know.
> 
> @Heyhillary We have updated the datasets to only include sentences that were generated from contributors. The new dataset has 30159 sentences and the data and description can be found [here](https://github.com/AI-Lab-Makerere/swahili-cv-validation/tree/master/data/batch-1-01-11-2021). We are working to secure agreement from some of the news websites to include their data in future PR's.

Awesome, thanks for making the changes. When you reach out to the publications, please use the [cc0 waiver process](https://common-voice.github.io/community-playbook/sub_pages/cc0waiver_process.html). Many thanks again for all your effort in amking this happen !

**Pull request merged**
