### PR TITLE
[Bulk submission] Added sentences for Abkhazian - batch 2

### PR DESCRIPTION
**Pull request by danielinux7**
- Number of sentences: 173,287
- Error ratio from the QA: > 95%
- Reviews: 
  - Astanda Akhuba:
[b2.300k.0.astanda.xlsx](https://github.com/common-voice/common-voice/files/8140998/b2.300k.0.astanda.xlsx)
[b2.300k.1.astanda.xlsx](https://github.com/common-voice/common-voice/files/8140999/b2.300k.1.astanda.xlsx)
[b2.300k.2.astanda.xlsx](https://github.com/common-voice/common-voice/files/8141001/b2.300k.2.astanda.xlsx)
  - Saria Argun: 
[b2.213k.0.saria.xlsx](https://github.com/common-voice/common-voice/files/8140995/b2.213k.0.saria.xlsx)
[b2.213k.1.saria.xlsx](https://github.com/common-voice/common-voice/files/8140997/b2.213k.1.saria.xlsx)
[b2.300k.1.saria.xlsx](https://github.com/common-voice/common-voice/files/8141000/b2.300k.1.saria.xlsx)
[b2.300k.2.saria.xlsx](https://github.com/common-voice/common-voice/files/8141002/b2.300k.2.saria.xlsx)
- The text is from eBooks that were released in public domain, here is [a link](https://github.com/danielinux7/abkhazian-books/blob/main/%D0%B0%D1%81%D1%82%D0%B0%D1%82%D0%B8%D1%81%D1%82%D0%B8%D0%BA%D0%B0/common-voice/batch2/batch2.md).

### CODE REVIEW

**Comment by Heyhillary** [comment]
Hey Daniel , is it possible to confirm in writing that texts for 2, 3 ,4 the latest living authors have passed away 70 years ago please ?

I also noticed that for the other texts that they had both a cc0 sticker and copyright, is it possible to explain how they got their cc0's please ?

**Comment by danielinux7** [comment]
Hello Hillary,

  > is it possible to confirm in writing that texts for 2, 3 ,4 the latest living authors have passed away 70 years ago please ?

Referring to [this link about copyright duration](https://www.bitlaw.com/copyright/duration.html), the 70 years rule applies to the work created on or after January 1, 1978.
The texts for 2, 3 and 4 were first published before 1950, therefore they entered the public domain.

  > is it possible to explain how they got their cc0's please ?

They got their cc0 from the book's publisher.

Please, let me know if you have any questions.

**Comment by Heyhillary** [comment]
Hey Nart, 

Thanks for following up. In principle it's okay for the text 2,3,4 to be added to the corpus due to the sentence being in the public domain.

Regarding the other works, could you connect me with Paul via email please ? As curently how the texts are uploaded have two incompatable licenses - which could cause legal issues. I am double checking with our legal team if we can accept them as is. Possibly we might have to the [formal cc0 waiver process ](https://common-voice.github.io/community-playbook/sub_pages/cc0waiver_process.html)(which covers texts added to the text corpus and not the entire work)  or the creative[ commons licnese cc0 process ](https://creativecommons.org/publicdomain/zero/1.0/legalcode)(which covers the text as a whole). 

Please let me know your thoughts.

**Comment by danielinux7** [comment]
Hello Hillary,

  > Regarding the other works, could you connect me with Paul via email please ?

Paul is not part of the other works, he is only part of 2, 3 and 4.

  > As curently how the texts are uploaded have two incompatable licenses

By marking CC0 is added to the copyright page, copyright notice shouldn't be removed.
I am referring the official [Creative Commons process](https://chooser-beta.creativecommons.org) for adding created work to CC0.

**Comment by Heyhillary** [comment]
Hey Nart, 

Thanks for your patience - I checked in with the team - you are good to go. 

@zaccolley or @mozgzh - would it be possible to add this submission please ?

**Pull request merged**
