### PR TITLE
Document the Return key shortcut for submitting clips.

### PR DESCRIPTION
**Pull request by Zopieux**
image

### CODE REVIEW

**Comment by phirework** [comment]
@mbransn can I get your eyes on this?

**Comment by mbransn** [comment]
Yeah, I think this submit got lost in translation at some point? Thought we had submit at one point. 

Anywho, good catch @Zopieux! My only change request is to utilize this icon instead to match with the rest of the site UI.
https://feathericons.com/?query=corner-down-left

**Comment by Zopieux** [comment]
Done, please take another look. Updated the screenshot. I had to add a new field to accommodate the icon.

**Comment by phirework** [comment]
Excellent, this looks great. Thanks @Zopieux!

**Pull request merged**
