### PR TITLE
Correct second person message

### PR DESCRIPTION
**Pull request by stuartlangridge**
To fix https://github.com/common-voice/common-voice/issues/4115

### Type of Pull Request

- [ ] Bulk sentence upload 

- [x] Related to a listed issue 

* https://github.com/common-voice/common-voice/issues/4115
*

- [ ] Other

*
*

### Acknowledging contributors

* Jess Rose

### CODE REVIEW

**Comment by moz-rotimib** [comment]
Hello @stuartlangridge thank you for your contribution.

Could you update this [test](https://github.com/common-voice/common-voice/blob/caac5f27bb5a813963ec051886bccf3629abc9b0/web/src/components/pages/datasets/dataset-download-email-prompt.test.tsx#L136) to look for `You want to join the Common Voice mailing list` instead? You just need to update `I` to `You` in the test assertion and this should be good to merge.

Once again thanks for your contribution and let me know if you have any questions

**Comment by stuartlangridge** [comment]
> Could you update this [test](https://github.com/common-voice/common-voice/blob/caac5f27bb5a813963ec051886bccf3629abc9b0/web/src/components/pages/datasets/dataset-download-email-prompt.test.tsx#L136) to look for `You want to join the Common Voice mailing list` instead? You just need to update `I` to `You` in the test assertion and this should be good to merge.

PR updated as requested!

**Comment by moz-rotimib** [comment]
Hello @stuartlangridge it seems you also need to make the same change you just made [here](https://github.com/common-voice/common-voice/blob/ed08e8d9844fba93b35775bc5c4d1381eab73e7d/web/src/components/pages/datasets/dataset-download-email-prompt.test.tsx#L198) and [here](https://github.com/common-voice/common-voice/blob/ed08e8d9844fba93b35775bc5c4d1381eab73e7d/web/src/components/pages/datasets/dataset-download-email-prompt.test.tsx#L257)

Sorry, I didn't see these earlier. The tests should be fine after these changes are made.

**Comment by stuartlangridge** [comment]
> Hello @stuartlangridge it seems you also need to make the same change you just made [here](https://github.com/common-voice/common-voice/blob/ed08e8d9844fba93b35775bc5c4d1381eab73e7d/web/src/components/pages/datasets/dataset-download-email-prompt.test.tsx#L198) and [here](https://github.com/common-voice/common-voice/blob/ed08e8d9844fba93b35775bc5c4d1381eab73e7d/web/src/components/pages/datasets/dataset-download-email-prompt.test.tsx#L257)
> 
> Sorry I didn't see these earlier. The tests should be fine after these changes are made.

Yup, my fault for not checking :) I think they're all changed now.

**Review by moz-rotimib — APPROVED** [review]
LGTM.

Thanks for your contribution 🎉

**Pull request merged**
