### PR TITLE
Logged In Profile UI updates

### PR DESCRIPTION
**Pull request by Dnouv**
As mentioned in Issue(#2314 ), there was a weird box. It is updated now, with new background color only for share icons. And, two new dividers are included as well in the footer. Regarding the first point, "the spacing between tabs..." appeared to me like already in the design. If there are any suggestions, please provide them. Here are the screenshots of the updated page.

On the page, before hovering on icons, there is also a divider at the bottom.
footer_noclick

On the page, after hovering on the icon(Twitter), the color is reversed. 
footer_after_hover

Dividers in the footer.
divider_footer

Feedbacks are most welcomed.

Thank You!

### CODE REVIEW

**Comment by phirework** [comment]
Hey, thanks so much for contributing this and welcome to the project! Just wanted to give you a heads up that the team is offline and undergoing an org-wide transition until March. I will review this once I'm back online. More info in this Discourse post: https://discourse.mozilla.org/t/update-on-common-voice-mozilla-foundation/74526/

Thanks for your patience!

**Comment by phirework** [comment]
Hello! Thanks for your patience and I appreciate your work. This PR has a few issues that need to be corrected before I can accept.  

1. Please do not add a whole new package just to fix a very minor cosmetic issue, that contributes unnecessary bloat to the codebase. I'm not actually clear why Material UI was added at all, since it doesn't seem like you're actually importing or using it anywhere. 
2. We would prefer that the social media icons remain the way they currently are on site, i.e. no background colour. 
3. We do actually want the dark grey box behind the social media icons to remain. The weird box that George Railean was referring to in the issue is an almost imperceptible purple overlay underneath the checkbox. 
4. Please follow existing naming conventions when naming your elements - the name of the element should be first, the modifier should follow the name of the element, and generally speaking we use dashes rather than underscores. In thise case, the elements would be better referred to as `.divider-vertical` and `.divider-bottom`

**Review by phirework — CHANGES_REQUESTED** [review]
Hello! Thanks for your patience and I appreciate your work. This PR has a few issues that need to be corrected before I can accept.

    Please do not add a whole new package just to fix a very minor cosmetic issue, that contributes unnecessary bloat to the codebase. I'm not actually clear why Material UI was added at all, since it doesn't seem like you're actually importing or using it anywhere.
    We would prefer that the social media icons remain the way they currently are on site, i.e. no background colour.
    We do actually want the dark grey box behind the social media icons to remain. The weird box that George Railean was referring to in the issue is an almost imperceptible purple overlay underneath the checkbox.
    Please follow existing naming conventions when naming your elements - the name of the element should be first, the modifier should follow the name of the element, and generally speaking we use dashes rather than underscores. In thise case, the elements would be better referred to as .divider-vertical and .divider-bottom

**Comment by Dnouv** [comment]
@phirework, thank you for your review; sorry, I was not aware of the standard naming conventions. I have fixed those names and removed the material-ui package.

**Comment by phirework** [comment]
Awesome, thanks for making the mods so quickly!

**Pull request merged**
