### PR TITLE
fix: Update Twitter Icon to X #4165

### PR DESCRIPTION
**Pull request by KSSaiTeja**
### Type of Pull Request
fixes: #4165 

- [ ] Bulk sentence upload 

- [x] Related to a listed issue 

* #4165 
*

- [ ] Other

* I have updated the twitter icon to new XIcon and also renamed the previous XIcon to XMarkIcon
*

### Acknowledging contributors

*
*

### CODE REVIEW

**Comment by KSSaiTeja** [comment]
> Hello @KSSaiTeja thanks for your contribution. I'll review and let you know if I have any comments ❤️

Okay.. i sincerely request to review my PR. as a beginner it would be more motivational to me.. Thank You!!

**Comment by KSSaiTeja** [comment]
@moz-rotimib Could you please let me know status of my PR.

**Comment by moz-rotimib** [comment]
> @moz-rotimib Could you please let me know status of my PR.

Hey @KSSaiTeja thanks for your contribution. I'll review your PR now and let you know if it's ok to get merged.

**Review by moz-rotimib — APPROVED** [review]
LGTM

**Comment by KSSaiTeja** [comment]
@moz-rotimib thanks for approving my PR. looking forward to contribute more

**Pull request merged**
