### PR TITLE
Add Lithuanian sentences

### PR DESCRIPTION
**Pull request by dvisockas**
Following the recommendation as in https://twitter.com/mikehenrty/status/1101564186578960384 to open a PR of sentences that I am confident in.

Don't know if I should everything piled up in one `sentence-collector.txt` file or should I add a new one.

### CODE REVIEW

**Comment by dvisockas** [comment]
Hey @MichaelKohler 

Moved the sentences to a separate file. 

Yes, these sentences come from a public domain source.
Data source: https://clarin.vdu.lt/xmlui/handle/20.500.11821/33
The licence does not require attribution: https://clarin.vdu.lt/licenses/eula/PUB_CLARIN-LT_End-User-Licence-Agreement_EN-LT.htm

Regarding the steps to enable the language - I have already localized most of the website (94%). I believe the lack of sentences is the main blocker to get the language added.

**Comment by MichaelKohler** [comment]
> Regarding the steps to enable the language - I have already localized most of the website (94%). I believe the lack of sentences is the main blocker to get the language added.

Indeed, sorry for that!

**Comment by phirework** [comment]
Hello! Thanks for submitting this. For large sentence corpuses like this we do require manual QA just to ensure sentence quality. This [Discourse post has the process](https://discourse.mozilla.org/t/using-the-europarl-dataset-with-sentences-from-speeches-from-the-european-parliament/50184) but the TLDR is that we need 2-3 native speakers to review a random sample of sentences to verify the following: 

* The sentences must be spelled correctly.
* The sentences must be grammatically correct.
* The sentences must be speakable (also avoiding non-native uncommon words)

We're looking for less than 5% of error rate on the random sample. For a corpus of ~44k sentences we're looking for a random sample of 3,800 sentences. Here's a [Google Spreadsheet template](https://docs.google.com/spreadsheets/d/1dJpysfcwmUwR4oJuw5ttGcUFYLeTbmn50Fpufz9qx-8/edit#gid=0) for reviewing, and here's a [sample PR](https://github.com/mozilla/common-voice/pull/2873) with the final reported info. 

Please note that Common Voice has been [significantly affected by the recent layoffs at Mozilla](https://discourse.mozilla.org/t/mozilla-org-wide-updates-impacts-on-common-voice/65612), and the project will have limited support as we work out a transition plan. I will try to get to these as soon as I can, we appreciate your patience.

**Comment by phirework** [comment]
Hey @dvisockas, wanted to follow up and see if you're able to provide a QA report for this batch?

**Comment by ftyers** [comment]
Going to close this as there has been no activity for over two years.

**Pull request closed without merging**
