### PR TITLE
adding over 240k armenian sentences from wikipedia

### PR DESCRIPTION
**Pull request by ekeleshian**
* 270,005 sentences
* source- wikipedia

I'm opening the PR ready to do whatever else needed to get it over the finish line

### CODE REVIEW

**Review by MichaelKohler — CHANGES_REQUESTED** [review]
Thanks for taking the effort to contribute to Common Voice!

Could you elaborate on how you created this export? Due to legal requirements we are only allowed to export a maximum of 3 sentences per article. For that reason we've created https://github.com/Common-Voice/cv-sentence-extractor. The following steps need to be taken to get Wikipedia sentences into the Common Voice corpus:

* Create a rules file as described in the README of https://github.com/Common-Voice/cv-sentence-extractor
* Create a blocklist to improve the quality of the sentences
* Create a PR which starts an automatic sample extract (GitHub Action)
* Use that sample to do the validation and record the validation result in a spreadsheet
* Once the desired low error rate is achieved, we merge the PR
* The official extraction is performed automatically and we'll create a PR for this repo with the sentences (this needs to be done through that process for legal reasons, so the rules and the blocklist is the only source, manual corrections of the sentences won't be possible)

You can find more info on the steps in the README. Here's an example of a merged PR where you can see the flow: https://github.com/common-voice/cv-sentence-extractor/pull/121. Also note the linked validation spreadsheet: https://docs.google.com/spreadsheets/d/1z7qS5FRNkIBMvYLgTy92zCnXhl6ynwOQazSRWhR0vd0/edit?usp=sharing

I'm happy to answer any questions you might have, feel free to ask questions at https://matrix.to/#/#common-voice-sentence-extractor:mozilla.org or open an issue in the extractor repo.

Side note: if you don't want to install all the required tools, feel free to create a draft PR and only use [the automatic sample extraction](https://github.com/common-voice/cv-sentence-extractor#automatic-extraction) to test it. Any new push to the PR will create a new sample extraction. You can also trigger the creation of a [blocklist without installing anything](https://github.com/common-voice/cv-sentence-extractor#create-a-blocklist-for-english---80-occurrences-threshold) locally.

**Comment by ekeleshian** [comment]
Thank you for your help! Wikiextractor doesn't work for armenian so I came up with my own script to extract the sentences while maintaining the requirement of 3 sentences per article. How I extracted the sentences and came up with the rules is by running this [script](https://github.com/ekeleshian/wikiextractor/blob/liz-branch/extract_sentences_hy.py)  Do I explicitly need a rules and block file and make it work with wikiextractor's extract program?

**Comment by MichaelKohler** [comment]
Why didn't it work? Was it because of https://github.com/common-voice/cv-sentence-extractor/issues/11?

@phirework do you have any thoughts here? I did a quick review of the script and it looks good to me. In the end I can't decide if we do exceptions or not.

**Comment by phirework** [comment]
Hmm, I think I'll have to confer with our legal folks to make sure we're okay on licensing. @ekeleshian Can you expand a little more on why Wikiextractor doesn't work for Armenian?

**Comment by ekeleshian** [comment]
wikiectractor assumes that the full stop indicator to a sentence is a period "."  In armenian the period is more like a semicolon.  Therefore, running wikiextractor on armenian leads to a combination of weird results: either splitting the text mid sentence, not splitting it at all, or splitting it in the middle of a collection of sentences.

**Comment by MichaelKohler** [comment]
@phirework this is a known issue with rust-punkt, see https://github.com/common-voice/cv-sentence-extractor/issues/11

**Comment by ftyers** [comment]
[Pragmatic segmenter](https://github.com/diasks2/pragmatic_segmenter) is great and supports Armenian. There is a partial Python reimplementation [here](https://github.com/kaine119/pygmatic-segmenter).

**Comment by ekeleshian** [comment]
@phirework any further questions to help push this along?

**Comment by ekeleshian** [comment]
> Hi @ekeleshian, thanks for your patience! We're good to go on a legal front. Have you done any sort of manual review or sampling of the output to make sure the sentences are correct (grammatically etc) as you'd expect?

A few volunteers and I are currently reviewing a sample of a little over 4,000 sentences using the google sheet template that was documented in the readme.

**Comment by phirework** [comment]
Excellent! Then this will be ready to merge as soon as that's done and you've confirmed the error rate is below 95%.

**Comment by MichaelKohler** [comment]
Happy to hear this will work out!

> you've confirmed the error rate is below 95%.

below 5% that is :)

**Comment by phirework** [comment]
Ha, yes, what @MichaelKohler said. Need more coffee :)

**Comment by MichaelKohler** [comment]
> Need more coffee :)

No worries, I'm sure I'm a few cups ahead :)

**Comment by ekeleshian** [comment]
- 244,867 Sentences
- Source: Wikipedia
-  3992 / 4087  sentences fully approved
- QA Sheets: [Eastern dialect](https://docs.google.com/spreadsheets/d/1sOXDzDrkmxwqkNK33QyEprlBLQ6yCA_JVTUohj02pKg/edit?usp=sharing) and [Western dialect](https://docs.google.com/spreadsheets/d/1kMgftA0-mK31U1klgmFcQCEAvPr_d8_Vc7zzu1f42fk/edit?usp=sharing) 
- Reviewers: [1](maroush@gmail.com) [2](ekeleshian@gmail.com) [3](keleshians@gmail.com)  (more emails to list, to be edited)

**Comment by MichaelKohler** [comment]
I'm deferring this review to @phirework . @ekeleshian would you mind calculating the overall error rate from all the reviews?

**Comment by ekeleshian** [comment]
> I'm deferring this review to @phirework . @ekeleshian would you mind calculating the overall error rate from all the reviews?

Error rate is 2.3%.

**Comment by phirework** [comment]
I'm comfortable not having the personal information of reviewers at this point, if we encounter any issues we'll reach out to you directly. This is good to merge and you're just before the cutoff for the next release, so you'll see these available to contribute in a few days. Thanks for all your work and diligence!

**Pull request merged**
