### PR TITLE
Contribution page fix

### PR DESCRIPTION
**Pull request by Dnouv**
As mentioned in issue #2880 , the components of "Contribution Activity" and "Top Contributors" were misaligned. I've fixed those cards. If there is any feedback or still any error, please feel free to provide it.

### CODE REVIEW

**Comment by Dnouv** [comment]
Apologies,
I forgot to put the screenshots of the updated pages. Here are both old and fixed page screenshots.
common-voice_web
This one is the page with the issue.

c-v_fixed
This is the fixed page screenshot.

Please feel free to provide feedback. I hope the changes can now be compared.
Thank you!

**Comment by phirework** [comment]
Hello, thanks for your patience! Most of this looks fine, but when the page is in LTR the labels are squished together. Can you take another look and ensure it works in both directions?

**Review by phirework — CHANGES_REQUESTED** [review]
Hello, thanks for your patience! Most of this looks fine, but when the page is in LTR the labels are squished together. Can you take another look and ensure it works in both directions?

**Comment by Dnouv** [comment]
Sorry @phirework, but could you please let me know what LTR is? Is it Left-to-Right written language?

**Comment by phirework** [comment]
Yep, that's correct! You can change the Common Voice language to something Arabic to see it organically, but during development you can use the inspector tool of whatever browser you're using to modify the `dir` attribute of the `html` element to `ltr`.

**Comment by ftyers** [comment]
> Yep, that's correct! You can change the Common Voice language to something Arabic to see it organically, but during development you can use the inspector tool of whatever browser you're using to modify the `dir` attribute of the `html` element to `ltr`.

Do you mean RTL  here ? e.g. Arabic is `dir="rtl"` i think, English is `dir="ltr"`.

**Comment by Dnouv** [comment]
@ftyers, I had the same doubt, but I have tested it for RTL; here is the screenshot. The labels were not squished together; please have a look.
cb-page_fix


Feedbacks are most welcomed. Thank you!

**Comment by phirework** [comment]
Yep sorry, I misspoke. Weird, I can't seem to reproduce it anymore, my bad. Congrats on your first PR!

**Pull request merged**
