### PR TITLE
Add sentences from public domain Ukrainian texts available at ukrlib.com.ua

### PR DESCRIPTION
**Pull request by somerandomguyontheweb**
This pull request contains sentences extracted from texts (prose, drama, essays) by Ukrainian authors who died 70+ years ago, between 1900 and 1951. Web editions of the texts were made available by the online library [UkrLib](https://www.ukrlib.com.ua). Likewise to a similar [bulk submission for Belarusian](https://github.com/common-voice/common-voice/pull/3161), we assume the source texts to be in public domain, as the copyright term has expired.

Please find [here](https://gist.github.com/somerandomguyontheweb/a87f821739018a02fedcde42a4c62518) a description of the sentence extraction procedure. At the time of writing (2021-11-03), the description provides a step-by-step guide how to extract a larger set of sentences, ca. 400K, from the source texts. Omitted is the filtering stage which includes multiple iterative refinements, intended to remove problematic sentences and bring down the error ratio.

- Number of sentences: 185'460
- Sample under review: [spreadsheet](https://docs.google.com/spreadsheets/d/16nr73H58LKd7N2Ylte-BFFmpdDuxdnmw/view)
- Error ratio: 4.9%

The review was done by @danmysak and @tamila-krashtan, native speakers of Ukrainian, who graciously offered their assistance with this PR and suggested many improvements to the sentence filtering procedure.

### CODE REVIEW

**Comment by phirework** [comment]
I think this is fine to merge, @Heyhillary can you confirm?

**Comment by Heyhillary** [comment]
Hey Jenny, just an update waiting for legal to review and then will confirm.

**Comment by Heyhillary** [comment]
Hey @phirework and @somerandomguyontheweb ,

Thanks for your patience. The legal team have reviewed the PR (not the code but the process), and we can accept the PR. 

The legal team have mentioned that for future PR please be cautious with automated collection and ensure that there is quality control check e.g cross referencing sentences with non-copyrighted texts. 

Many thanks again for creating this PR and your teams contribution !

**Comment by phirework** [comment]
Great, thanks for following back up @Heyhillary!

**Pull request merged**
