### PR TITLE
Carme bsc

### PR DESCRIPTION
**Pull request by c-armentano**
### Type of Pull Request

- [x] Bulk sentence upload 

- [ ] Related to a listed issue 

- [ ] Other

Sentences generated with substitution templates for this project with wikidata data, published [here](https://github.com/TeMU-BSC/catalan_CC0_sentences) for the first time.

* Number of sentences: 18550
* Error ratio from the QA: 2%
* Reviews: [1](https://docs.google.com/spreadsheets/d/1DrsDS1Swhb9peice_ICxr5g__GZME2HYg7eE9vSOVAw/edit?usp=sharing) & [2](https://docs.google.com/spreadsheets/d/1MH-HS1a2MHcXHCd29wrjUv9Wjb_2UOUm6-uIpeyM818/edit?usp=sharing)

### Acknowledging contributors
 

* @jmontane 
* @asier-gutierrez

### CODE REVIEW

**Comment by c-armentano** [comment]
I also added the file "marius_serra_sentences_1.txt", with 9917 sentences by Marius Serra, who [agrees](https://github.com/TeMU-BSC/catalan_CC0_sentences/blob/main/contribution_agmt/Permi%CC%81s%20AINA.jpeg) to share part of his work with the Common Voice project.

* Number of sentences: 9917
* Error ratio from the QA: 2%
* Reviews [1](https://docs.google.com/spreadsheets/d/1d2ioywWlHE0ix4z4upAGdXGIwsI22QaAFXgwATo5taU/edit?usp=sharing) & [2](https://docs.google.com/spreadsheets/d/176aibe1Ts5YDsxO9cI7Q3vwx_BS-l9sAQjHjfNsT9CU/edit?usp=sharing)

**Comment by Heyhillary** [comment]
Hey Carme, 

Thanks for the PR request @zaccolley or @mozgzh is it possible to add the first part of the[ PR request please ](https://github.com/common-voice/common-voice/pull/3469#issue-1141423092).

Regarding the second part, we would need to have the name of the articles (e.g the publishing name) that Marius would like to include for the agreement, as there is a section on page 3 of the form where this needs to be written. I have also shared the form with the Mozilla Legal to team to authorise signing. 

Many thanks for the new sentences !

**Comment by c-armentano** [comment]
Thank you.

**Comment by zaccolley** [comment]
@Heyhillary @c-armentano If only part of this PR is ready to be merged we can either submit it as a seperate pull request or we can wait until the rest of the PR is approved too. I'm not 100% sure which parts are approved and which aren't sorry!

**Comment by c-armentano** [comment]
Hey  @zaccolley ,
I've removed the not accepted part. I'll do a new PR with it when the issue will be solved.

**Comment by zaccolley** [comment]
Thank you @c-armentano ❤️ 

@Heyhillary can you confirm everything in this PR is ready to go?

**Comment by Heyhillary** [comment]
> I also added the file "marius_serra_sentences_1.txt", with 9917 sentences by Marius Serra, who [agrees](https://github.com/TeMU-BSC/catalan_CC0_sentences/blob/main/contribution_agmt/Permi%CC%81s%20AINA.jpeg) to share part of his work with the Common Voice project.
> 
>     * Number of sentences: 9917
> 
>     * Error ratio from the QA: 2%
> 
>     * Reviews [1](https://docs.google.com/spreadsheets/d/1d2ioywWlHE0ix4z4upAGdXGIwsI22QaAFXgwATo5taU/edit?usp=sharing) & [2](https://docs.google.com/spreadsheets/d/176aibe1Ts5YDsxO9cI7Q3vwx_BS-l9sAQjHjfNsT9CU/edit?usp=sharing)

Hey @carme is it possible to share what the name of the texts Marius would like to add. We will have to go through the formal cc0 process and a e-document will be sent to Marius. In order to I would need to know the name of the texts. 
If you have any questions please let me know.

**Comment by c-armentano** [comment]
Hey, @Heyhillary .

I removed marius_serra_sentences_1.txt from this PR, and added a file with all Marius serra’s sentences called marius_serra_sentences.txt in this other one: https://github.com/common-voice/common-voice/pull/3495

They are extracted from the following works:

Books:
    • La Napeu 
    • Fora de joc a Montserrat 
    • Jugar-s'hi la vida 
    • La novel·la de Sant Jordi 
    • D'on trec el temps 
    • Hawaii Lima 
    • Plans de futur 
    • L'arca de Babel 
    • De com s'escriu una novel·la 
    • Enviar i rebre 
    • Farsa 
    • La vida normal 
    • L'home del sac 
    • La llegenda de Sant Jordi 
    • Mon oncle 
    • Quiet 
    • Res no és perfecte a Hawaii 
    • Tres és massa 
    • Verbàlia 
Mots encreuats (crosswords)
Marrius Serra's [blog](http://enigmisticamarius.blogspot.com/).

I’ll send you the documents by email. Please, let me know if there is any problem and if I can help on it.

Thank you.

**Comment by Heyhillary** [comment]
Hey @c-armentano , Is it possible if you could please make a second PR for marius_serra_sentences_1.txt.

MoFo legal team have now signed. Thanks for your patience.

**Comment by c-armentano** [comment]
Hi, Hillary.
I did a new PR with a file called marius_serra_sentences.txt. 
https://github.com/common-voice/common-voice/pull/3495
marius_serra_sentences.txt includes the sentences that were in marius_serra_sentences_1.txt + other sentences, all form the works I listed.

**Comment by Heyhillary** [comment]
Hey Camre, 

Thanks sorry I just noticed the PR. Thanks for also adding it here.

**Pull request merged**
