### PR TITLE
OI-2492

### PR DESCRIPTION
**Pull request by moz-rotimib**
## OI-2492 Metadata expansion on Speak UI individual clips

- Adds a check box for accepting terms and privacy before submitting. Previously, this was done via a modal - the modal is still visible when the user tries to abort before uploading 5 clips
- Remove the share button from the recording pill

https://user-images.githubusercontent.com/113194143/199770020-ac38bc92-9a42-4ebe-8e64-da5f8ab6e7c1.mov

### CODE REVIEW

**Comment by mozgzh** [comment]
Looks good! One thought, should the button be disabled or change colour based on the state of "privacyAgreedChecked", ie if the ToS aren't checked, grey out, once agreed, blue?

**Comment by moz-rotimib** [comment]
> Looks good! One thought, should the button be disabled or change colour based on the state of "privacyAgreedChecked", ie if the ToS aren't checked, grey out, once agreed, blue?

In the designs Sabrina shared, the button does not change colour depending on the state of "privacyAgreedChecked". If you try to submit the clips without checking the box, you are prevented from doing so until the box is checked

Screenshot 2022-11-18 at 13 23 13

**Comment by mozgzh** [comment]
Cool, that should be fine if its in the design. Last question, how does it look on mobile?

**Comment by moz-rotimib** [comment]
> Cool, that should be fine if its in the design. Last question, how does it look on mobile?

This is how it looks on the iPhone emulator in Firefox


https://user-images.githubusercontent.com/113194143/202707925-611a7adf-3577-44d1-b388-8ff5ef5704ef.mov

**Pull request closed without merging**
