### PR TITLE
Make Partner logo clickable to redirect towards partner site...

### PR DESCRIPTION
**Pull request by Jash2606**
### Type of Pull Request

- [x] Related to a listed issue 

* Issue  #4569 

### Issue Description
*Problem:* The "Our Partners" section on our website currently displays partner logos as static images. Users cannot click on these logos to be redirected to the respective partner websites. This limits user engagement and does not help in validating our partners through direct access to their official sites.

*Solution:* Convert the partner logos into clickable links that redirect users to the corresponding partner websites. This enhancement will improve user experience, increase engagement, and provide validation for our partners.

### Testing
1. Verified that each logo is clickable and redirects to the correct partner website.
2. Checked that links open in a new tab.
3. Ensured that the layout and design of the "Our Partners" section remains consistent and visually appealing.

### CODE REVIEW

**Comment by Jash2606** [comment]
Hey @moz-dfeller @moz-rotimib or another maintainer ,

Could you please review it and merge it ?

**Comment by moz-rotimib** [comment]
Hey @Jash2606 thanks for your contribution. I'll review this PR soon and let you know if it's good to merge or if there are changes needed.

**Comment by moz-rotimib** [comment]
Hey @Jash2606 thanks once again for your contribution. I have a comment regarding your PR - could you wrap the images in an anchor tag instead of adding a click handler to the img tag like you have currently? 

Images shouldn't have click handlers so it would be better if you wrapped the image in an anchor tag and added the URL to the href attribute.

So it would look something like this:

```jsx
            <a
              href="https://www.gatesfoundation.org/"
              target="_blank"
              rel="noreferrer">
              <img
                src={require('./images/partners/Bill_&_Melinda_Gates_Foundation_logo.jpg')}
                srcSet={`${require('./images/partners/Bill_&_Melinda_Gates_Foundation_logo-small.jpg')} 370w, ${require('./images/partners/Bill_&_Melinda_Gates_Foundation_logo.jpg')} 741w`}
                sizes="(max-width: 600px) 370px, 741px"
                alt="Bill and Melinda Gates Foundation"
                width={370}
                height={135}
              />
            </a>
```

**Comment by Jash2606** [comment]
> Hey @Jash2606 thanks once again for your contribution. I have a comment regarding your PR - could you wrap the images in an anchor tag instead of adding a click handler to the img tag like you have currently?
> 
> Images shouldn't have click handlers so it would be better if you wrapped the image in an anchor tag and added the URL to the href attribute.
> 
> So it would look something like this:
> 
> ```js
>             <a
>               href="https://www.gatesfoundation.org/"
>               target="_blank"
>               rel="noreferrer">
>                                src={require('./images/partners/Bill_&_Melinda_Gates_Foundation_logo.jpg')}
>                 srcSet={`${require('./images/partners/Bill_&_Melinda_Gates_Foundation_logo-small.jpg')} 370w, ${require('./images/partners/Bill_&_Melinda_Gates_Foundation_logo.jpg')} 741w`}
>                 sizes="(max-width: 600px) 370px, 741px"
>                 alt="Bill and Melinda Gates Foundation"
>                 width={370}
>                 height={135}
>               />
>             </a>
> ```

Hey @moz-rotimib ,

Done with changes , Could you review it and let me know if further changes required .

**Comment by moz-rotimib** [comment]
Looks good @Jash2606 thanks for your contribution

**Review by moz-rotimib — APPROVED** [review]

**Pull request merged**
