### PR TITLE
Add Wikipedia DE re-run - 2022-01-09

### PR DESCRIPTION
**Pull request by MichaelKohler**
This adds the DE (German) Wikipedia Re-run of 2022-01-09. The rules updates were previously validated. This adds 250k new sentences. Once again I had to split up into multiple runs, as the amount was simply too much:

2019-07-20 - 2019-09-30: https://github.com/common-voice/cv-sentence-extractor/actions/runs/1674910491
2019-10-01 - 2019-12-31: https://github.com/common-voice/cv-sentence-extractor/actions/runs/1674911490
2020-01-01 - 2020-03-31: https://github.com/common-voice/cv-sentence-extractor/actions/runs/1674912303
2020-04-01 - 2020-06-30: https://github.com/common-voice/cv-sentence-extractor/actions/runs/1674940083
2020-07-01 - 2020-09-30: https://github.com/common-voice/cv-sentence-extractor/actions/runs/1674940715
2020-10-01 - 2020-12-31: https://github.com/common-voice/cv-sentence-extractor/actions/runs/1674941257
2021-01-01 - 2021-03-31: https://github.com/common-voice/cv-sentence-extractor/actions/runs/1674941937
2021-04-01 - 2021-06-30: https://github.com/common-voice/cv-sentence-extractor/actions/runs/1674942666
2021-07-01 - 2021-09-30: https://github.com/common-voice/cv-sentence-extractor/actions/runs/1674943387
2021-10-01 - 2021-12-31: https://github.com/common-voice/cv-sentence-extractor/actions/runs/1674943864
2022-01-01 - 2022-01-10: https://github.com/common-voice/cv-sentence-extractor/actions/runs/1674944638

cc @stefangrotz @guerda

### CODE REVIEW

**Comment by guerda** [comment]
Hi Michael!
Do you need any feedback on this?

**Comment by MichaelKohler** [comment]
No, that was just for your information, all good :)

**Comment by stefangrotz** [comment]
Great work. thanks!

**Comment by phirework** [comment]
You rock, thank you!

**Pull request merged**
