### PR TITLE
Added  90,000 sentences for Luganda

### PR DESCRIPTION
**Pull request by jmukiibi**
### Type of Pull Request

- [X ] Bulk sentence upload
- Added 90,000 validated Luganda sentences 
- Source of Sentences: Created by the Community members and validated by Linguists 
- Licence: CC0 sentences

### License: CC0
Link to the [lincense](https://github.com/AI-Lab-Makerere/luganda-cv-validation/blob/master/LICENSE.md): 
More details on validation and sentence contribution can be found [here](https://github.com/AI-Lab-Makerere/luganda-cv-validation/tree/master/validations).
Validation [repository](https://github.com/AI-Lab-Makerere/luganda-cv-validation) for Luganda CV

### Acknowledging contributors and Partners

*Marconi Lab
*Makerere AI Lab
*Department of African Languages (Makerere University)
*The Buganda Kingdom

### CODE REVIEW

**Comment by jmukiibi** [comment]
@Heyhillary help me review this PR if you have some time on you.

**Comment by Heyhillary** [comment]
Heya @jmukiibi 

Could you please add the agreement or email the cco license for these sources please:

*Marconi Lab
*Makerere AI Lab
*Department of African Languages (Makerere University) 

Even if it's a github link

**Comment by jmukiibi** [comment]
Hi, @Heyhillary and @mozgzh I hope the details provided are enough. We have planned a voice contribution drive for Luganda this Thursday. I hope by any chance we can have these sentences released....maybe maybe..

**Comment by Heyhillary** [comment]
Thank you will merge

**Pull request merged**
