### PR TITLE
Add PCCD Catalan dataset (CC0)

### PR DESCRIPTION
**Pull request by pereorga**
### Type of Pull Request

- [x] Bulk sentence upload 

[Paremiologia Catalana Comparada Digital](https://pccd.dites.cat/) (**PCCD** for short) is an online collection of Catalan proverbs, idioms, and other sentences in Catalan made by [Víctor Pàmies i Riudor](https://refranys.wordpress.com/). This pull request is for adding the main PCCD dataset to Common Voice under the [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) license.

The original PCCD dataset is bigger. Here we are only adding the main, more general Catalan sentences ("paremiotipus"). Additionally, some sentences have been omitted:

- Sentences that are too short or too long.
- Sentences that contain inappropriate language.
- Sentences that already exist (or that are very similar) in existing Common Voice Catalan datasets. Note that the PCCD is already a "user" of Common Voice, as we incorporate CV voices when they exist (e.g., see the top right block in https://pccd.dites.cat/p/Qui_no_vulgui_pols%2C_que_no_vagi_a_l%27era)
- Sentences that do not pass LanguageTool rules in https://github.com/Softcatala/filter-wiki-corpus-lt/blob/master/src/main/java/softcatala/filterwikicorpus/filterwikicorpus.java. I was advised by @jaumeortola, developer of LanguageTool, who also has experience with previous imports in Common Voice.

### Acknowledging contributors

- Víctor Pàmies i Riudor is the author and copyright holder of the work. See https://twitter.com/vpamies/status/1558397095907835904
- [Softcatalà](https://www.softcatala.org/) hosts and develops the PCCD and acts as a technical partner.

### CODE REVIEW

**Comment by pereorga** [comment]
Proof that author has given permission: https://twitter.com/vpamies/status/1558397095907835904

Please advise if additional steps are necessary.

**Comment by Heyhillary** [comment]
Hey @pereorga 

Thanks for creating this PR.

I noticed on your [website ](https://pccd.dites.cat/credits )that you have the sentences are "[Creative Commons Atribució-NoComercial-CompartirIgual 4.0 Internacional](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.ca)." 

The tweet is not enough to be CC0.

The author can either dedicate the cc0 using the [CC0 waiver process](https://common-voice.github.io/community-playbook/sub_pages/cc0waiver_process.html) for the sentence in this PR. 

Or the author [can use this ](https://creativecommons.org/choose/zero/)

**Comment by pereorga** [comment]
Hi @Heyhillary 

This is correct, the PCCD is currently released under a more restrictive license. At this point in time there is no plan to change the current license.

We are happy to follow the CC0 waiver process for the selected sentences available in this pull request. We have emailed you asking for further information.

Thanks
Pere

**Comment by c-armentano** [comment]
Hi!
I'm looking forward to see these new sentences! Is there any update about them?
Thanks!

**Comment by pereorga** [comment]
The PR has been updated, and it now includes additional sentences.

I have sent a reminder to @Heyhillary via email.

**Comment by pereorga** [comment]
The PR has been updated with the latest PCCD database, removing/adding some sentences.

**Comment by pereorga** [comment]
Hi @ftyers, @moz-dfeller,

Is there anything else we could do to speed up the review process? I think this contribution is of good quality, as the sentences have been reviewed. We are very eager to see this merged.

**Comment by pereorga** [comment]
Thanks @moz-dfeller! Any idea when this will be deployed and people will start pronouncing sentences? Not sure the progress can be publically followed. I would like to start importing it the other way around soon (CV -> PCCD).

**Pull request merged**
