### PR TITLE
fix create table accents the size of utf8mb4

### PR DESCRIPTION
**Pull request by ranaawni**
### Type of Pull Request

- [x] Bulk sentence upload 

- [x] Related to a listed issue 

*
*

- [x] Other

*
*

### Acknowledging contributors

*
*

### CODE REVIEW

**Comment by ranaawni** [comment]
I fix it and change the size of accent_name and accent_token from 255 to 191

**Comment by zaccolley** [comment]
@ranaawni Hey Rana, thanks for the PR, could we get a bit more info as to what this fixes?

**Comment by ranaawni** [comment]
> 

@zaccolley

**Comment by zaccolley** [comment]
@ranaawni Can I double check which database you're using for this? Are you using Docker to run the project?

@mozgzh Any thoughts on this?

**Comment by ranaawni** [comment]
@zaccolley  yes I'm using Docker

**Comment by mozgzh** [comment]
Hi, thanks for opening the PR! 

Just a quick walk through of the columns being changed: 

- ```client_id CHAR(36)``` is an optional key that must be CHAR(36). 
- Changing the other VARCHAR sizes would require an `ALTER`, and since data already exists, a full migration would be needed to ensure all existing data could fit in the new constraint.

 The issue doesn't seem to affect others and I'm not too sure how changing the size of the columns would affect the creation of the table.

**Pull request closed without merging**
