### PR TITLE
Fix luganda typo

### PR DESCRIPTION
**Pull request by jmukiibi**
Fixed typos identified by the voice contributors

### CODE REVIEW

**Comment by phirework** [comment]
Hey @jmukiibi - I'm happy to merge this, but I wanted to give you a heads up that we don't have a good mechanism to swap out bad sentences, so the original sentences with typos will still be in our database. If your users notice the mistaken sentences, please go ahead and report them.

**Comment by jmukiibi** [comment]
> Hey @jmukiibi - I'm happy to merge this, but I wanted to give you a heads up that we don't have a good mechanism to swap out bad sentences, so the original sentences with typos will still be in our database. If your users notice the mistaken sentences, please go ahead and report them.

If they report them, do I have to send in a PR with the new changes as I have done or its another kind of reporting?

**Comment by phirework** [comment]
They can report using the button in the visual interface and we'll log it in the database automatically. 
Screen Shot 2021-04-06 at 3 10 43 PM

**Comment by jmukiibi** [comment]
Thanks.

**Pull request merged**
