### PR TITLE
Implement profile download (aka takeout), scaling to large users

### PR DESCRIPTION
**Pull request by Zopieux**
This is inspired by #1210 PR. I've adapted some of the frontend code from it.

#### Notes to upstream/maintainers
* As mentioned in https://github.com/common-voice/common-voice/pull/2865#issuecomment-846426670 the code doing the actual zipping would benefit from being hosted as an AWS Lambda, and since Lambda is nodejs-enabled, it should actually be super trivial to 1. port [the archiving code](https://github.com/common-voice/common-voice/pull/3133/files#diff-c7af0cc31a9dc5a1644eca91565cebd2b8afcc10c9eb035c116869af1d3a44dbR148-R171) to Lambda and 2. swap it for a Lambda invocation.
* This PR assumes you'll configure an [S3 lifecycle](https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-configuration-examples.html#lifecycle-config-ex1) for the takeout zips. The cleanup worker **does not** emit S3 deletion requests. I think lifecycle configs are a better mechanism because we cannot "forget" to delete archives & it avoids extra S3 API queries. I've added a `Type=takeout` tagging in the code (commented out for now because it breaks s3proxy, maybe it should be a config value), so the S3 lifecycle filter should be on that tag.
* Security and privacy: this PR assumes none of the S3 bucket objects are available publicly without signing the URL, because otherwise exports would be susceptible to an enumeration attack (if the attacker knows the victim's UUID, then they can just append `/takeout/X/Y.zip`).
* I did not added new config key/value pairs for the various [magic numbers](https://github.com/common-voice/common-voice/pull/3133/files#diff-a7e35ae5e72b14b5d61cc4320c906c87e3bdb2195f266cfcd1ba946461cd154eR10-R21) introduced in this PR, but maybe we should.

#### Features
* New "Download my data" page, which replaces the one-click export of the profile to a text file
* That page allows selecting for profile and/or recordings
* If recordings are requested, then a background process starts to compile all recordings into one or multiple ZIP files, on the backend, using the Bull queuing library (depends on Redis)
* The page lists pending and completed recording requests
* For completed requests, a _Download_ button displays a modal with the actual AWS S3 links to the ZIP file(s)
* For pending requests, a _Refresh_ button can be clicked to refresh the pending requests
* Automatic clean-up of both failed/abandoned/completed-but-expired requests
* The user is prevented from creating multiple pending exports (cheap DoS prevention)

#### Meta changes

* Added dependency on s3zip and bull
* Added redis to the docker-compose, so this can be tested during development
* Published the s3proxy port to 9001 so we can check downloading the files work
* Renamed the latest migration that had a typo in the name (2121 instead of 2021)
* Refactored `bytesToSize` so I can reuse it
* Removed some unused imports
* Some whitespace edits were automatically done by the precommit hook

Screenshots below (80% zoom for convenience).

----
image

----
image

----
image

----
image

### CODE REVIEW

**Comment by phirework** [comment]
This is amazing, thank you for putting in the work and talking through your thought process in #2865. I will try to do a more detailed review this week, but in the meantime can I get you to edit/resubmit this PR and merge to the `takeout-zopieux` branch I've just pushed instead of `main`? I'd like to be able to selectively deploy this for testing before the full feature gets merged.

**Comment by Zopieux** [comment]
Thanks for your quick reply! Rebased against `takeout-zopieux`, and update this PR target, is that what you wanted?

**Comment by phirework** [comment]
Yep that's perfect, thanks! Also tagging in @mbransn for UX/copy review.

**Comment by Zopieux** [comment]
Added important notes to the PR description aimed at reviewers / repository owners.

**Comment by ftyers** [comment]
I had a quick look at the code but couldn't tell, @Zopieux will this separate the clips into subdirectories in the zip by language? e.g. `takeout/ca`, `takeout/eu`, `takeout/pt` etc. ?

**Comment by phirework** [comment]
It doesn't, nor does it generate a list of sentences or any other metadata/segmentation, it just zips up mp3 files on an S3 bucket. This isn't (and shouldn't be imo) a fully fledged dataset export, not until we've actually evaluated what that would mean for server load.

**Comment by ftyers** [comment]
@phirework sounds good to me :) (and sorry for the PR noise)

**Comment by phirework** [comment]
No worries! Totally valid question.

**Comment by mbransn** [comment]
> Yep that's perfect, thanks! Also tagging in @mbransn for UX/copy review.

This is looking great, thanks to @Zopieux for the solid work! @phirework let me know when this is on stage and I'll do a more granular QA against a couple other components? copy looks great to me. :)

**Comment by Zopieux** [comment]
If you think this will require a lot of changes to be correctly integrated, feel free to take over this work and close this :-)

**Comment by phirework** [comment]
Hey @Zopieux, sorry for the much longer than anticipated delay. I've looked at this and it looks great, super clean + good commenting. I really appreciate the work that went into it! I've got a few small changes (some cosmetic things and localization tweaks, some db structure things, changing some of the default vars), but I'm happy to make those changes myself, so I'm going to merge this in and get it up on staging for testing. Would you like to be pinged when that's ready for testing or do you just want a heads up when it deploys to prod?

**Comment by Zopieux** [comment]
Hey @phirework thanks for the kind words, glad I could help.

I don't mind testing your latest changes once they are ready, sadly I won't have access to my setup until next week. If you want to get it released before that, please go ahead, if it can wait I can have a look early next week. Cheers.

**Comment by JayBeavers** [comment]
Is there an ETA for this to hit the hosted project website?

**Comment by phirework** [comment]
Hey @JayBeavers, thanks for your patience! This is now on the production website behind a feature-flag, and we're looking for beta testers. Please get in touch with @Heyhillary if you're interested in helping out!

**Comment by JayBeavers** [comment]
Interested in helping out.  Don't see an email addr on the profile for @Heyhillary.  How do I contact her, submit a pull request on her personal github repo?  :-)

**Comment by ftyers** [comment]
You could also try @heyhillary on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org). :)

**Pull request merged**
