### PR TITLE
feat: add Hebrew sentence validation

### PR DESCRIPTION
**Pull request by kwikwag**
## Pull Request Form

Adds Hebrew sentence validation.

Hopefully another pull request will include removal of already-submitted sentences that aren't valid - though this should be done delicately (see comments regarding punctuation allow in the English validator that was made invalid in the Hebrew validator).

It adds one eslint warning regarding the use of `require` - I didn't want to touch it as all other validators use this syntax.

### Type of Pull Request

- [ ] Bulk sentence upload 
- [x] Related to a listed issue 
  * https://github.com/common-voice/common-voice/issues/4121

### Acknowledging contributors

Just me; coordinated with @moz-dfeller .

### CODE REVIEW

**Comment by kwikwag** [comment]
Hey @moz-dfeller ! Is there any thing I can do to help move this forward?

**Comment by moz-dfeller** [comment]
Looks good! Just one things that is missing, could you add one or two sentences that you would consider to validate correctly and one or two that should not be valid in [./validation/validation.test.ts](https://github.com/common-voice/common-voice/tree/main/server/src/test/core/pending-sentences/validation/validation.test.ts). That would be great, thanks!

**Review by moz-dfeller — CHANGES_REQUESTED** [review]
Looks good to me! Thank you for your contribution.

**Comment by kwikwag** [comment]
Hey @moz-dfeller ! I just pushed another commit. I added tests. While I was at it I fixed some subtle nuances in the Hebrew validation rules.

I took the liberty of adding two convenience functions in testing that seemed useful for writing more succinct code - hopefully that doesn't violate a style guide. Perhaps later I can refactor existing tests to use these functions.

**Comment by kwikwag** [comment]
P.S. This would also be a good time to run validations against existing sentences in the existing corpus; I would expect many sentences to fail -- however would only bother removing those that match the Hebrew cantillation marks pattern. Let me know if there is any way I can help move this forward.

**Comment by kwikwag** [comment]
Hey @moz-dfeller a reminder - any updates? Can I do anything to help get this merged?

**Review by moz-dfeller — APPROVED** [review]
Hey there! Thank you for the very detailed validation rules and the tests! Thank for you patience as well. It will be merged and part of the next release 🎉

**Pull request merged**
