### PR TITLE
Add lug batch3

### PR DESCRIPTION
**Pull request by jmukiibi**
New 7117 sentences created by the CV community using custom pontoon. 
Error ratio of 98% after QA

[Link to review GitHub excel document where validation was done ](https://github.com/jmukiibi/cv-validation)
Link to custom [Pontoon](https://airnlp.herokuapp.com/) where we translate our community sentences from English to Luganda.

### CODE REVIEW

**Comment by jmukiibi** [comment]
@phirework, are you available to look into my commit. Thanks

**Comment by phirework** [comment]
Hi @jmukiibi, there is a merge conflict with one of your previous batches of sentences, can you please review?

**Comment by jmukiibi** [comment]
@phirework I have resolved them. I hope you are still in position to work on this.

**Comment by phirework** [comment]
The core team is offline until March, but this will be released with the next release in a few weeks.

**Comment by jmukiibi** [comment]
Thanks.

**Pull request merged**
