### PR TITLE
[th] Add singleword benchmark for Thai

### PR DESCRIPTION
**Pull request by bact**
Thai words for digits 0-9, yes, no, hey, and Firefox.

### CODE REVIEW

**Comment by phirework** [comment]
Can you confirm whether these have been vetted with fluent Thai speakers?

**Comment by bact** [comment]
> Can you confirm whether these have been vetted with fluent Thai speakers?

Has asked people around to confirm that in this GitHub issue. May take sometime for responses.
(I'm also a fluent Thai speaker)

**Comment by veer66** [comment]
> Can you confirm whether these have been vetted with fluent Thai speakers?

I assure you that I am a fluent Thai speaker and these are single words are valid Thai words.

**Comment by srakrn** [comment]
I can confirm the correctness of these Thai single words as a native speaker.

**Comment by LXZE** [comment]
> Can you confirm whether these have been vetted with fluent Thai speakers?

I am a native Thai speaker and confirm that all of these Thai words in the list correspond to their English meaning.

**Comment by mishari** [comment]
I'm a native speaker and can confirm as such

**Comment by rtsp** [comment]
I'm native Thai speaker and confirm that all those single words are correct.

**Comment by sitdh** [comment]
All those words are correct as a native speaker.

**Comment by BLeAm** [comment]
I'm a native Thai speaker and I can confirm that all these single words are correct.

**Comment by narze** [comment]
I confirm that all those words are all correct 👍

**Comment by MichaelKohler** [comment]
Thanks everyone! I think we have enough confirmations now :)

**Comment by phirework** [comment]
Thanks everyone!

**Pull request merged**
