### PR TITLE
Add Wikipedia DE re-run - 2022-08-16

### PR DESCRIPTION
**Pull request by MichaelKohler**
### Type of Pull Request

- [x] Bulk sentence upload 

- [ ] Related to a listed issue 

- [ ] Other

This adds a new Wikipedia extract re-run for German. As the last export was done on 2022-01-10, this export includes the time period of 2022-01-11 until today. The list of new titles is attached as well for future reference as needed: [new-article-titles.txt](https://github.com/common-voice/common-voice/files/9354728/new-article-titles.txt)

Extraction run: https://github.com/common-voice/cv-sentence-extractor/actions/runs/2870032209

### CODE REVIEW

**Comment by MichaelKohler** [comment]
@ftyers can we merge this?

**Comment by MichaelKohler** [comment]
This conforms to the 3 sentences per article maximum rule that is in place in Sentence Extractor.

**Comment by MichaelKohler** [comment]
@jessicarose I think at this point this could be integrated, right?

**Comment by ginamoape** [comment]
Hey @MichaelKohler, should we continue with merging this PR?

**Comment by MichaelKohler** [comment]
@ginamoape yes, please :)

**Pull request merged**
