### PR TITLE
Underline

### LINKED ISSUE #4573: UI Enhancment
Enhance the user experience by adding hover effects to the "About," "Discourse," and "Contact" links.

When a user hovers over any of the links, change the text color or underline the text.
Ensure the hover effect is smooth and consistent across all links.

WhatsApp Image 2024-08-04 at 23 27 06

### PR DESCRIPTION
**Pull request by Adityajaiswal03**
This PR adds underline when links are hovered over
Screenshot 2024-08-04 at 11 39 00 PM

This PR resolve #4573

### CODE REVIEW

**Comment by HarikalarKutusu** [comment]
Just a quick Q: Did you check it with dark browser themes?

**Comment by Adityajaiswal03** [comment]
No @HarikalarKutusu   just lemme check once and  get back to you

**Comment by Adityajaiswal03** [comment]
Hi @HarikalarKutusu, I changed my browser settings to dark mode, but the website remained in light mode. It seems there isn't a dark mode available at the moment.

**Comment by HarikalarKutusu** [comment]
Sorry for your time, I was remembering the issue belowand thought that it could be done. Maybe it is browser specific.
https://github.com/common-voice/common-voice/issues/3644

I use dark mode in Windows and VS Code, but not on browsers (need of contrast).

**Comment by Adityajaiswal03** [comment]
@HarikalarKutusu No worries. I look forward to receiving more feedback from you soon.

**Review by moz-dfeller — APPROVED** [review]

**Comment by moz-dfeller** [comment]
Thank you very much for your contribution! 🚀  @Adityajaiswal03

**Pull request merged**
