### PR TITLE
Add Belarusian sentences from Novy Chas

### PR DESCRIPTION
**Pull request by somerandomguyontheweb**
This pull request contains sentences extracted from news stories published by the Belarusian newspaper [Novy Chas](https://novychas.by). As of 2021-08-12, tentative permission has been obtained from the editorial to use their sentences as CC0, but no formal agreement has been signed yet. To secure the agreement, we're going to follow the [procedure](https://github.com/common-voice/community-playbook/blob/draft/sub_pages/cc0waiver_process.md) drafted by @Heyhillary.

Please find [here](https://gist.github.com/somerandomguyontheweb/2125c138f10f27be8f017d3ea742a043) a detailed description of the sentence extraction procedure. This procedure is intended to be fully reproducible.

- Number of sentences: 55'576
- Sample under review: [spreadsheet](https://docs.google.com/spreadsheets/d/1JCE1SisxWqPJnCVij0tFqto9DXdyfwea/edit)
- Error ratio: 1.1%

### CODE REVIEW

**Comment by phirework** [comment]
This is great, thanks @somerandomguyontheweb! Please let me know once the agreement has been signed.

**Comment by somerandomguyontheweb** [comment]
As advised by @Heyhillary, I'm removing sentences that come from non-original stories, i.e. reprinted by _Novy Chas_ from other sources (these data cannot be licensed as CC0). The submission has 52'620 sentences now.

**Comment by Heyhillary** [comment]
Hiya, writing to confirm the agreement has been signed by all relevant parties.

**Comment by phirework** [comment]
Wonderful news, thanks @Heyhillary!

**Pull request merged**
