### PR TITLE
Listen page fix for unchecked index

### PR DESCRIPTION
**Pull request by HarikalarKutusu**
## Pull Request Form

- [x ] Related to a listed issue 

*  https://github.com/common-voice/common-voice/issues/3747

While debugging this issue I found an unchecked edge case. The `getClipIndex` function can return `-1`, but it is directly used to index the `clips` array. The function is used in many places, but this is the point where it is used to retrieve the `activeClip`, which further can result `isMissingClips` becoming `true`, which might cause the problem. Even if it is not related, in any case, such index range checking is necessary.

### CODE REVIEW

**Review by moz-dfeller — APPROVED** [review]
Good catch, thank you so much! 🚀

**Review by moz-rotimib — APPROVED** [review]

**Comment by moz-rotimib** [comment]
@HarikalarKutusu there's a merge conflict in this PR now. Could you resolve it so it can be merged? Thanks ❤️

**Comment by HarikalarKutusu** [comment]
I resolved this through the GitHub interface, mine was a single line.

I think there is a misconfiguration for semicolon use though. The files and the .prettierrc do not match. Therefore, whenever I use VS Code for a PR, it makes many unnecessary changes. Maybe reviewing .prettierrc, adding some settings in the .vscode folder, and running yarn prettier globally will help this (I tried and it modified 8xx files).

**Comment by moz-rotimib** [comment]
> I resolved this through the GitHub interface, mine was a single line.
> 
> I think there is a misconfiguration for semicolon use though. The files and the .prettierrc do not match. Therefore, whenever I use VS Code for a PR, it makes many unnecessary changes. Maybe reviewing .prettierrc, adding some settings in the .vscode folder, and running yarn prettier globally will help this (I tried and it modified 8xx files).

That's fine. The prettierc config was changed to remove semi-colons but this file hasn't been updated to use that config yet.

**Pull request merged**
