### PR TITLE
Added 1239 Luganda sentences.

### PR DESCRIPTION
**Pull request by jmukiibi**
Number of sentences: 1239

QA error rate on a random sample of 955: 0%

Review [1](https://github.com/AI-Lab-Makerere/luganda-cv-validation/blob/master/batch-thirteen/validator1%20-%20Sentence%20verification%20process.xlsx) [2](https://github.com/AI-Lab-Makerere/luganda-cv-validation/blob/master/batch-thirteen/validator2%20-%20Sentence%20verification%20process.xlsx) [3](https://github.com/AI-Lab-Makerere/luganda-cv-validation/blob/master/batch-thirteen/validator3%20-%20Sentence%20verification%20process.xlsx)

### CODE REVIEW

**Comment by jmukiibi** [comment]
@phirework could you be having some time to look into our Luganda PRs? We just don't want to miss out on the next release.

Thanks,

**Comment by phirework** [comment]
Hi @jmukiibi, the next platform release is next Wednesday July 28th (the dates are listed in the README.md of this repo) so as long as all your merges are in before then it's fine. Since releases are every two weeks, it might also be easier if you batch your new sentence PRs into bigger chunks of sentences instead of adding them all separately. This would also resolve the issue where some of your PRs include commits from other PRs that was causing the conflict a few weeks ago.

**Comment by jmukiibi** [comment]
@phirework Thanks a lot for the information. It's just that as a community goal, we decided to make sure we make daily PRs because we also have daily validation exercises ongoing locally. It kind of stimulates the community to be active but also creates the urge for everyone to see whether the PRs have been merged or not. But I do get your side of the story.

Regards.

**Comment by phirework** [comment]
@jmukiibi Got it, I didn't realize that was a community activation effort, that's really cool. Feel free to continue!

**Pull request merged**
