### PR TITLE
Catalan language update for banner-error-slow

### PR DESCRIPTION
**Pull request by gullabi**
Minor correction to the "slow" prompt in the banner to make it more appropriate.

### Type of Pull Request

- [ ] Bulk sentence upload 

- [ ] Related to a listed issue 

- [X] Other

* Minor language correction

### CODE REVIEW

**Comment by Heyhillary** [comment]
Hey @gullabi ,

Thanks for your PR. The Common Voice Platform is localised via pontoon by volunteers.

If you would like to make a change: [please use this link](https://pontoon.mozilla.org/ca/common-voice/)

**Comment by gullabi** [comment]
Hi Hillary thanks for the instruction but I cannot find the string in pontoon. I am suspecting that pontoon takes the strings from another branch and this string is only in the production branch.

**Comment by zaccolley** [comment]
@gullabi Yes you're right, I'll sync up our main branch that Pontoon uses. Thank you!

**Comment by zaccolley** [comment]
@gullabi Should be in Pontoon for you to change now, thank you so much! I will close this PR for now, let us know how you get on.

**Pull request closed without merging**
